[editor]
cursorline = true
color-modes = true
trim-trailing-whitespace = true

[editor.lsp]
signature-help-position = "below"

[editor.statusline]
center = ["file-type"]

[keys.select]
"C-`" = "switch_to_uppercase"

[keys.normal]
C-j = "jump_view_down"
C-k = "jump_view_up"
C-h = "jump_view_left"
C-l = "jump_view_right"
C-b = "@ b%id "
