[[language]]
name = "python"
auto-format = true

[language.config.pylsp.plugins]
flake8 = {enabled = true}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = true}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
ruff = { enabled = true, ignore = ["F401"], lineLength = 120 }

[language-server.elixir-ls.config]
elixirLS.dialyzerEnabled = true