# Arduino
[language-server.arduino-language-server]
command = "arduino-language-server"
args = ["-log", "-logpath", "/tmp"]

[[language]]
name = "arduino"
scope = "source.arduino"
injection-regex = "arduino"
file-types = ["ino"]
roots = ["sketch.yaml"]
indent = { tab-width = 2, unit = "  " }
formatter = { command = "clang-format" , args = ["--style=llvm", "%{buffer_name}"]}
language-servers = [ "arduino-language-server" ]

[[grammar]]
name = "arduino"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-arduino", rev = "ce02903e3ae74c729e9415dc32c276447b1c8afd" }

# C++
[[language]]
name = "cpp"
auto-format = true
formatter = {command = "clang-format", args=["--style=llvm", "%{buffer_name}"]}

[language-server.clangd]
command = "clangd"

# Elixir
[[language]]
name = "elixir"
text-width = 100

[language-server.elixir-ls.config]
config = { elixirLS.dialyzerEnabled = true }

# Python
[[language]]
name = "python"
auto-format = true

# XML
[[language]]
name = "xml"
file-types = ["xml", "mobileconfig", "plist", "xib", "storyboard", "svg", "xsd", "gml", "xaml", "gir", "xacro"]

# YAML
[[language]]
name = "yaml"
file-types = ["yml", "yaml", "rviz"]

