[[language]]
name = "python"
auto-format = true

[[language]]
name = "elixir"
text-width = 100

[[language]]
name = "xml"
file-types = ["xml", "mobileconfig", "plist", "xib", "storyboard", "svg", "xsd", "gml", "xaml", "gir", "xacro"]

[[language]]
name = "yaml"
file-types = ["yml", "yaml", "rviz"]

[language-server.clangd]
command = "clangd"
args=["--compile-commands-dir=."]

[language-server.elixir-ls.config]
elixirLS.dialyzerEnabled = true
