[language-server]
clangd = { command = "clangd", args=["--compile-commands-dir=compile_commands_directory"] }

[[language]]
name = "python"
auto-format = true

[language-server.elixir-ls.config]
elixirLS.dialyzerEnabled = true

[[language]]
name = "xml"
file-types = ["xml", "mobileconfig", "plist", "xib", "storyboard", "svg", "xsd", "gml", "xaml", "gir", "xacro"]

[[language]]
name = "yaml"
file-types = ["yml", "yaml", "rviz"]

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = " " }
