
[general]
import = ["/home/jb/.config/alacritty/themes/dracula-pro.toml"]

[bell]
animation = "EaseOutExpo"
duration = 100

[font]
size = 10

[window]
decorations = "None"
opacity = 0.98

[window.dimensions]
columns = 100
lines = 50

[keyboard]

[[keyboard.bindings]]
key = "Enter"
mods = "Control|Shift"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "Enter"
mods = "Alt"
action = "ToggleMaximized"
