# Colors (Mar)
colors:
  # Default Colors
  primary:
    background: '0xffffff'
    foreground: '0x4d4d4c'
  # Normal colors
  normal:
    black:    '0x000000'
    red:      '0xc82828'
    green:    '0x718c00'
    yellow:   '0xeab700'
    blue:     '0x4171ae'
    magenta:  '0x8959a8'
    cyan:     '0x3e999f'
    white:    '0xfffefe'
  # Bright colors
  bright:
    black:    '0x000000'
    red:      '0xC82828'
    green:    '0x718C00'
    yellow:   '0xEAB700'
    blue:     '0x4171AE'
    magenta:  '0x8959A8'
    cyan:     '0x3E999F'
    white:    '0xFFFEFE'
