# Colors (Dichromacy)
colors:
  # Default Colors
  primary:
    background: '0xffffff'
    foreground: '0x000000'
  # Normal colors
  normal:
    black:    '0x000000'
    red:      '0xe69f00'
    green:    '0x009e73'
    yellow:   '0xf8ec59'
    blue:     '0x0072b2'
    magenta:  '0xcc79a7'
    cyan:     '0x56b4e9'
    # white:    '0x848ea9'
    white:    '0xd55e00'
  # Bright colors
  bright:
    black:    '0x202020'
    red:      '0xfeaf00'
    green:    '0x00daa0'
    yellow:   '0xf8e820'
    blue:     '0x008cda'
    magenta:  '0xcc4089'
    cyan:     '0x56d0e9'
    white:    '0xf56c00'
