# Colors (One Light)
colors:
  # Default Colors
  primary:
    background: '0xf8f8f8'
    foreground: '0x2a2b32'
  # Normal colors
  normal:
    black:    '0x000000'
    red:      '0xda3e39'
    green:    '0x41933e'
    yellow:   '0x855504'
    blue:     '0x315eee'
    magenta:  '0x930092'
    cyan:     '0x0e6fad'
    white:    '0x8e8f96'
  # bright colors
  bright:
    black:    '0x2a2b32'
    red:      '0xda3e39'
    green:    '0x41933e'
    yellow:   '0x855504'
    blue:     '0x315eee'
    magenta:  '0x930092'
    cyan:     '0x0e6fad'
    white:    '0xfffefe'
