[openai]  # each supported api has their own config section with api and url
api_key_command = "pass Keys/OpenAI/jay@appliedinvention.com"
default_model = "gpt-5"
url = "https://api.openai.com/v1/chat/completions"

[anthropic]
api_key_command = "pass Keys/Anthropic/jbromley@gmail.com"
url = "https://api.anthropic.com/v1/messages"
default_model = "claude-sonnet-4-20250514"
version = "2023-06-01"  # anthropic API version, see https://docs.anthropic.com/en/api/versioning

[ollama]  # local API, no key required
url = "http://localhost:11434/api/chat"
default_model = "phi3"
timeout_seconds = 180  # default timeout if not specified
