[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[cmd_duration]
min_time = 5

[erlang]
symbol = "ⓔ "

[nodejs]
symbol = "[⬢](bold green) "
