# See the full configuration reference: https://rioterm.com/docs/config
confirm-before-quit = false
copy-on-select = true
draw-bold-text-with-light-colors = true
theme = "IR_Black"

[fonts]
size = 14
family = "JetBrains Mono"
user-drawable-chars = true
symbol-map = [
  { start = "23FB", end = "23FE", font-family = "Symbols Nerd Font Mono" },
  { start = "2630", end = "2630", font-family = "Symbols Nerd Font Mono" },
  { start = "2665", end = "2665", font-family = "Symbols Nerd Font Mono" },
  { start = "26A1", end = "26A1", font-family = "Symbols Nerd Font Mono" },
  { start = "276C", end = "2771", font-family = "Symbols Nerd Font Mono" },
  { start = "2B58", end = "2B58", font-family = "Symbols Nerd Font Mono" },
  { start = "E000", end = "E00A", font-family = "Symbols Nerd Font Mono" },
  { start = "E0A0", end = "E0A3", font-family = "Symbols Nerd Font Mono" },
  { start = "E0B0", end = "E0C8", font-family = "Symbols Nerd Font Mono" },
  { start = "E0CA", end = "E0CA", font-family = "Symbols Nerd Font Mono" },
  { start = "E0CC", end = "E0D2", font-family = "Symbols Nerd Font Mono" },
  { start = "E0CA", end = "E0CA", font-family = "Symbols Nerd Font Mono" },
  { start = "E0D4", end = "E0D4", font-family = "Symbols Nerd Font Mono" },
  { start = "E0D6", end = "E0D7", font-family = "Symbols Nerd Font Mono" },
  { start = "E200", end = "E2A9", font-family = "Symbols Nerd Font Mono" },
  { start = "E300", end = "E3E3", font-family = "Symbols Nerd Font Mono" },
  { start = "E5FA", end = "E687", font-family = "Symbols Nerd Font Mono" },
  { start = "E700", end = "E8E3", font-family = "Symbols Nerd Font Mono" },
  { start = "EA60", end = "EA88", font-family = "Symbols Nerd Font Mono" },
  { start = "EA8A", end = "EA8C", font-family = "Symbols Nerd Font Mono" },
  { start = "EA8F", end = "EAC7", font-family = "Symbols Nerd Font Mono" },
  { start = "EAC9", end = "EAC9", font-family = "Symbols Nerd Font Mono" },
  { start = "EACC", end = "EB09", font-family = "Symbols Nerd Font Mono" },
  { start = "EB0B", end = "EB4E", font-family = "Symbols Nerd Font Mono" },
  { start = "EB50", end = "EC1E", font-family = "Symbols Nerd Font Mono" },
  { start = "ED00", end = "EFCE", font-family = "Symbols Nerd Font Mono" },
  { start = "F000", end = "F381", font-family = "Symbols Nerd Font Mono" },
  { start = "F400", end = "F533", font-family = "Symbols Nerd Font Mono" },
  { start = "F0001", end = "F1AF0", font-family = "Symbols Nerd Font Mono" }
]

[editor]
program = "hx"
args = []

[bindings]
keys = [
  { key = "[", with = "control", action = "SelectPrevSplit"},
  { key = "]", with = "control", action = "SelectNextSplit"},
  { key = "1", with = "control | shift", action = "SelectTab(0)"},
  { key = "2", with = "control | shift", action = "SelectTab(1)"},
  { key = "3", with = "control | shift", action = "SelectTab(2)"},
  { key = "4", with = "control | shift", action = "SelectTab(3)"},
  { key = "5", with = "control | shift", action = "SelectTab(4)"},
  { key = "6", with = "control | shift", action = "SelectTab(5)"},
  { key = "7", with = "control | shift", action = "SelectTab(6)"},
  { key = "8", with = "control | shift", action = "SelectTab(7)"},
  { key = "9", with = "control | shift", action = "SelectTab(8)"},
  { key = "0", with = "control | shift", action = "SelectTab(9)"}
]

[navigation]
unfocused-split-opacity = 0.9

[title]
content = "{{ program }} - {{ absolute_path }}"

[window]
opacity = 0.8
