[colors]
cursor = { text = 'CellForeground', cursor = '#ebeafa' }
selection = { text = 'CellForeground', background = '#6b527d' }
indexed_colors = [
    { index = 16, color = '#452859' },
    { index = 17, color = '#573e74' },
    { index = 18, color = '#6a568f' },
    { index = 19, color = '#7d6eac' },
    { index = 20, color = '#9086ca' },
    { index = 21, color = '#a4a0e8' },
    { index = 22, color = '#5b4e65' },
    { index = 23, color = '#675f7a' },
    { index = 24, color = '#727090' },
    { index = 25, color = '#7e82a6' },
    { index = 26, color = '#8a95bd' },
    { index = 27, color = '#95a8d4' },
    { index = 28, color = '#6f7571' },
    { index = 29, color = '#748080' },
    { index = 30, color = '#798b90' },
    { index = 31, color = '#7d97a0' },
    { index = 32, color = '#81a3b0' },
    { index = 33, color = '#85aec1' },
    { index = 34, color = '#809d7c' },
    { index = 35, color = '#7fa286' },
    { index = 36, color = '#7ca68f' },
    { index = 37, color = '#79ab99' },
    { index = 38, color = '#75b0a3' },
    { index = 39, color = '#71b4ae' },
    { index = 40, color = '#90c786' },
    { index = 41, color = '#87c48a' },
    { index = 42, color = '#7dc28e' },
    { index = 43, color = '#72bf92' },
    { index = 44, color = '#66bd96' },
    { index = 45, color = '#59ba9a' },
    { index = 46, color = '#9ff28f' },
    { index = 47, color = '#8de88d' },
    { index = 48, color = '#7bdd8c' },
    { index = 49, color = '#67d38a' },
    { index = 50, color = '#51c988' },
    { index = 51, color = '#35bf86' },
    { index = 52, color = '#69365d' },
    { index = 53, color = '#784c77' },
    { index = 54, color = '#866292' },
    { index = 55, color = '#9478af' },
    { index = 56, color = '#a28fcc' },
    { index = 57, color = '#afa6e9' },
    { index = 58, color = '#7a5a69' },
    { index = 59, color = '#846a7e' },
    { index = 60, color = '#8d7b94' },
    { index = 61, color = '#958cab' },
    { index = 62, color = '#9d9dc2' },
    { index = 63, color = '#a4aeda' },
    { index = 64, color = '#8a7e74' },
    { index = 65, color = '#8e8984' },
    { index = 66, color = '#919496' },
    { index = 67, color = '#949fa7' },
    { index = 68, color = '#96aab9' },
    { index = 69, color = '#98b5cb' },
    { index = 70, color = '#98a27e' },
    { index = 71, color = '#97a78a' },
    { index = 72, color = '#94ad97' },
    { index = 73, color = '#92b2a3' },
    { index = 74, color = '#8eb7af' },
    { index = 75, color = '#8abcbc' },
    { index = 76, color = '#a5c889' },
    { index = 77, color = '#9dc790' },
    { index = 78, color = '#96c697' },
    { index = 79, color = '#8dc59e' },
    { index = 80, color = '#84c4a5' },
    { index = 81, color = '#7ac2ac' },
    { index = 82, color = '#b0ee92' },
    { index = 83, color = '#a2e695' },
    { index = 84, color = '#95df97' },
    { index = 85, color = '#86d799' },
    { index = 86, color = '#77d09b' },
    { index = 87, color = '#66c99d' },
    { index = 88, color = '#8b4660' },
    { index = 89, color = '#975a7a' },
    { index = 90, color = '#a16e95' },
    { index = 91, color = '#ab82b1' },
    { index = 92, color = '#b397ce' },
    { index = 93, color = '#bbaceb' },
    { index = 94, color = '#99676b' },
    { index = 95, color = '#a07682' },
    { index = 96, color = '#a68598' },
    { index = 97, color = '#ab95b0' },
    { index = 98, color = '#b0a4c8' },
    { index = 99, color = '#b3b4e0' },
    { index = 100, color = '#a48776' },
    { index = 101, color = '#a79289' },
    { index = 102, color = '#a99c9b' },
    { index = 103, color = '#aba7ae' },
    { index = 104, color = '#abb1c1' },
    { index = 105, color = '#abbcd5' },
    { index = 106, color = '#afa881' },
    { index = 107, color = '#aead8f' },
    { index = 108, color = '#acb39e' },
    { index = 109, color = '#a9b8ac' },
    { index = 110, color = '#a6bebb' },
    { index = 111, color = '#a1c4ca' },
    { index = 112, color = '#b8c88b' },
    { index = 113, color = '#b2c996' },
    { index = 114, color = '#adc9a0' },
    { index = 115, color = '#a6caaa' },
    { index = 116, color = '#9fcab5' },
    { index = 117, color = '#97cbbf' },
    { index = 118, color = '#bfea96' },
    { index = 119, color = '#b6e59c' },
    { index = 120, color = '#ace0a2' },
    { index = 121, color = '#a2dba8' },
    { index = 122, color = '#97d6ae' },
    { index = 123, color = '#8bd2b3' },
    { index = 124, color = '#ae5664' },
    { index = 125, color = '#b5687d' },
    { index = 126, color = '#bc7b98' },
    { index = 127, color = '#c18db3' },
    { index = 128, color = '#c4a0cf' },
    { index = 129, color = '#c6b2ec' },
    { index = 130, color = '#b7746e' },
    { index = 131, color = '#bb8285' },
    { index = 132, color = '#bf909c' },
    { index = 133, color = '#c19eb4' },
    { index = 134, color = '#c2accd' },
    { index = 135, color = '#c2bbe6' },
    { index = 136, color = '#be9079' },
    { index = 137, color = '#c09a8d' },
    { index = 138, color = '#c1a4a1' },
    { index = 139, color = '#c1aeb5' },
    { index = 140, color = '#c0b9ca' },
    { index = 141, color = '#bdc3df' },
    { index = 142, color = '#c5ad84' },
    { index = 143, color = '#c4b394' },
    { index = 144, color = '#c2b8a5' },
    { index = 145, color = '#c0bfb6' },
    { index = 146, color = '#bdc5c7' },
    { index = 147, color = '#b8cbd8' },
    { index = 148, color = '#cac98e' },
    { index = 149, color = '#c7cb9c' },
    { index = 150, color = '#c3cda9' },
    { index = 151, color = '#becfb7' },
    { index = 152, color = '#b9d1c4' },
    { index = 153, color = '#b3d3d1' },
    { index = 154, color = '#cee599' },
    { index = 155, color = '#c8e3a3' },
    { index = 156, color = '#c2e1ad' },
    { index = 157, color = '#bbdfb7' },
    { index = 158, color = '#b4dcc1' },
    { index = 159, color = '#addacb' },
    { index = 160, color = '#d16766' },
    { index = 161, color = '#d47780' },
    { index = 162, color = '#d6889a' },
    { index = 163, color = '#d698b5' },
    { index = 164, color = '#d5a8d1' },
    { index = 165, color = '#d0b9ee' },
    { index = 166, color = '#d58171' },
    { index = 167, color = '#d78d88' },
    { index = 168, color = '#d89aa0' },
    { index = 169, color = '#d7a7b9' },
    { index = 170, color = '#d4b4d2' },
    { index = 171, color = '#d0c1eb' },
    { index = 172, color = '#d8997b' },
    { index = 173, color = '#d9a391' },
    { index = 174, color = '#d9aca7' },
    { index = 175, color = '#d7b6bc' },
    { index = 176, color = '#d4c0d3' },
    { index = 177, color = '#cfcae9' },
    { index = 178, color = '#dbb186' },
    { index = 179, color = '#dab899' },
    { index = 180, color = '#d9bead' },
    { index = 181, color = '#d6c5c0' },
    { index = 182, color = '#d3cbd3' },
    { index = 183, color = '#cfd2e7' },
    { index = 184, color = '#dcc991' },
    { index = 185, color = '#dacca2' },
    { index = 186, color = '#d8d0b3' },
    { index = 187, color = '#d5d3c3' },
    { index = 188, color = '#d2d7d4' },
    { index = 189, color = '#cddae5' },
    { index = 190, color = '#dbe19d' },
    { index = 191, color = '#d9e1ab' },
    { index = 192, color = '#d7e1b9' },
    { index = 193, color = '#d4e2c7' },
    { index = 194, color = '#d0e2d4' },
    { index = 195, color = '#cce2e2' },
    { index = 196, color = '#f47868' },
    { index = 197, color = '#f38782' },
    { index = 198, color = '#f0959d' },
    { index = 199, color = '#eca3b8' },
    { index = 200, color = '#e5b1d3' },
    { index = 201, color = '#dbbfef' },
    { index = 202, color = '#f48e73' },
    { index = 203, color = '#f3998b' },
    { index = 204, color = '#f0a5a4' },
    { index = 205, color = '#ecb0be' },
    { index = 206, color = '#e7bcd7' },
    { index = 207, color = '#dec8f1' },
    { index = 208, color = '#f3a27e' },
    { index = 209, color = '#f2ab95' },
    { index = 210, color = '#f0b4ac' },
    { index = 211, color = '#edbec4' },
    { index = 212, color = '#e8c7db' },
    { index = 213, color = '#e2d0f3' },
    { index = 214, color = '#f0b689' },
    { index = 215, color = '#f0bd9e' },
    { index = 216, color = '#efc4b4' },
    { index = 217, color = '#edcbca' },
    { index = 218, color = '#e9d2e0' },
    { index = 219, color = '#e5d9f6' },
    { index = 220, color = '#edc994' },
    { index = 221, color = '#edcea8' },
    { index = 222, color = '#edd3bc' },
    { index = 223, color = '#ecd7d0' },
    { index = 224, color = '#ebdce4' },
    { index = 225, color = '#e8e1f8' },
    { index = 226, color = '#e8dca0' },
    { index = 227, color = '#eadfb2' },
    { index = 228, color = '#ebe1c4' },
    { index = 229, color = '#ece4d6' },
    { index = 230, color = '#ece7e8' },
    { index = 231, color = '#ebeafa' },
    { index = 232, color = '#4b2f5f' },
    { index = 233, color = '#513665' },
    { index = 234, color = '#583d6b' },
    { index = 235, color = '#5e4471' },
    { index = 236, color = '#644b77' },
    { index = 237, color = '#6b527d' },
    { index = 238, color = '#715a83' },
    { index = 239, color = '#78618a' },
    { index = 240, color = '#7e6990' },
    { index = 241, color = '#857096' },
    { index = 242, color = '#8b789d' },
    { index = 243, color = '#9280a3' },
    { index = 244, color = '#9987a9' },
    { index = 245, color = '#9f8fb0' },
    { index = 246, color = '#a697b7' },
    { index = 247, color = '#ad9fbd' },
    { index = 248, color = '#b3a7c4' },
    { index = 249, color = '#baafca' },
    { index = 250, color = '#c1b8d1' },
    { index = 251, color = '#c8c0d8' },
    { index = 252, color = '#cfc8df' },
    { index = 253, color = '#d6d0e5' },
    { index = 254, color = '#ddd9ec' },
    { index = 255, color = '#e4e1f3' },
]
[colors.primary]
background = '#452859'
foreground = '#ebeafa'
[colors.normal]
black = '#697c81'
red = '#f47868'
green = '#9ff28f'
yellow = '#e8dca0'
blue = '#a4a0e8'
magenta = '#dbbfef'
cyan = '#35bf86'
white = '#ebeafa'
[colors.bright]
black = '#77568b'
red = '#f22c86'
green = '#35bf86'
yellow = '#ffcd1c'
blue = '#6f44f0'
magenta = '#9445ae'
cyan = '#9ff28f'
white = '#ffffff'
